name: "clang format"

on:
  pull_request:
    branches: ["main"]
    paths:
      - 'src/**/*.cpp'
      - 'src/**/*.hpp'
      - '.github/**/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  clang-format-linter:
    if: ${{ github.repository == 'mjschmidt271/koPP_particleCode' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: mjschmidt271/clang-format-lint-action@f/add-invocation
      continue-on-error: false
      id: run-clang-format
      with:
        source: './src/test-format'
        exclude: ''
        extensions: 'hpp,cpp'
        clangFormatVersion: 14
        style: llvm
