name: "clang format"

# if .{cpp,hpp} files are touched in a PR, lint them!

on:
  pull_request:
    branches: ["main"]
    paths:
      - 'src/**/*.cpp'
      - 'src/**/*.hpp'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  clang-format-linter:
    if: ${{ github.repository == 'mjschmidt271-koPP_particleCode' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    # - uses: tj-actions/changed-files@v46
    #   id: changed-files
    #   with:
    #     files: 'src/**/*.{cpp,hpp}'
    #     separator: " "
    # displays the diff, comparing to the changes that *would* be made
    - uses: mjschmidt271/clang-format-lint-action@v0.0.1
      with:
        source: './src'
        exclude: ''
        extensions: 'hpp,cpp'
        clangFormatVersion: 14
        style: llvm
